from argus_header.markdown import render_markdown, save_markdown


def sample_report():
    return {
        "tool": {
            "name": "Argus Header",
            "version": "0.7.0",
        },
        "scan": {
            "target": "https://example.com",
            "final_url": "https://example.com/",
            "status": 200,
            "method": "GET",
            "timestamp": "2026-08-22T00:00:00+00:00",
            "duration_seconds": 0.4213,
        },
        "score": {
            "value": 80,
            "grade": "B",
            "risk_level": "HIGH",
            "penalty": 20,
        },
        "summary": {
            "total_findings": 1,
            "high": 1,
            "medium": 0,
            "low": 0,
        },
        "findings": [
            {
                "id": "SEC-001",
                "category": "Security",
                "issue": "Missing Content-Security-Policy",
                "severity": "HIGH",
                "risk": "XSS risk.",
                "fix": "Add CSP.",
            }
        ],
        "headers": {
            "Content-Type": "text/html",
        },
    }


def test_markdown_report():
    markdown = render_markdown(sample_report())

    assert "# Argus Header Security Report" in markdown
    assert "80 / 100 — Grade B" in markdown
    assert "SEC-001" in markdown
    assert "Missing Content-Security-Policy" in markdown
    assert "Content-Type" in markdown


def test_markdown_clean_site():
    report = sample_report()
    report["findings"] = []
    report["summary"] = {"total_findings": 0, "high": 0, "medium": 0, "low": 0}
    report["headers"] = {}

    markdown = render_markdown(report)

    assert "✅ No significant security issues found." in markdown
    assert "No response headers available." in markdown


def test_markdown_escapes_pipes_in_header_values(tmp_path):
    report = sample_report()
    report["headers"] = {
        "Content-Security-Policy": "default-src 'self'; frame-ancestors |none|"
    }

    markdown = render_markdown(report)

    assert "\\|none\\|" in markdown


def test_save_markdown_writes_file(tmp_path):
    file_path = tmp_path / "report.md"

    save_markdown(sample_report(), str(file_path))

    content = file_path.read_text(encoding="utf-8")

    assert "# Argus Header Security Report" in content
    assert "Generated by Argus Header 0.7.0" in content
