"""Markdown report renderer for Argus Header."""

from pathlib import Path


def render_markdown(report: dict) -> str:
    """Render a canonical report dictionary as Markdown."""

    tool = report["tool"]
    scan = report["scan"]
    score = report["score"]
    summary = report["summary"]
    findings = report.get("findings", [])
    headers = report.get("headers", {})

    lines = []

    lines.append(f"# {tool['name']} Security Report")
    lines.append("")

    lines.append("## Scan Information")
    lines.append("")
    lines.append(f"- **Target:** `{scan['target']}`")
    lines.append(f"- **Final URL:** `{scan.get('final_url', scan['target'])}`")
    lines.append(f"- **Status:** `{scan.get('status', 'N/A')}`")
    lines.append(f"- **Method:** `{scan.get('method', 'GET')}`")
    lines.append(f"- **Timestamp:** `{scan.get('timestamp', 'N/A')}`")
    lines.append(f"- **Duration:** `{scan.get('duration_seconds', 0):.4f}s`")
    lines.append("")

    lines.append("## Security Score")
    lines.append("")
    lines.append(f"**{score['value']} / 100 — Grade {score['grade']}**")
    lines.append("")
    lines.append(f"- **Risk Level:** {score['risk_level']}")
    lines.append(f"- **Penalty:** {score['penalty']}")
    lines.append("")

    lines.append("## Findings Summary")
    lines.append("")
    lines.append(f"- **Total:** {summary['total_findings']}")
    lines.append(f"- **High:** {summary['high']}")
    lines.append(f"- **Medium:** {summary['medium']}")
    lines.append(f"- **Low:** {summary['low']}")
    lines.append("")

    lines.append("## Findings")
    lines.append("")

    if not findings:
        lines.append("✅ No significant security issues found.")
        lines.append("")
    else:
        for finding in findings:
            lines.append(
                f"### [{finding.get('severity', 'UNKNOWN')}] "
                f"{finding.get('issue', 'Unknown issue')}"
            )
            lines.append("")
            lines.append(f"- **Rule ID:** `{finding.get('id', 'N/A')}`")
            lines.append(f"- **Category:** {finding.get('category', 'N/A')}")
            lines.append(f"- **Risk:** {finding.get('risk', 'N/A')}")
            lines.append(f"- **Fix:** {finding.get('fix', 'N/A')}")
            lines.append("")

    lines.append("## Response Headers")
    lines.append("")

    if headers:
        lines.append("| Header | Value |")
        lines.append("|---|---|")

        for name, value in headers.items():
            safe_value = str(value).replace("|", "\\|")
            lines.append(f"| `{name}` | `{safe_value}` |")

        lines.append("")
    else:
        lines.append("No response headers available.")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by {tool['name']} {tool['version']}*")
    lines.append("")

    return "\n".join(lines)


def save_markdown(report: dict, filepath: str) -> None:
    """Render and save a Markdown report."""

    content = render_markdown(report)

    Path(filepath).write_text(
        content,
        encoding="utf-8",
    )
